@echo off
echo Скачиваем Resource Hacker...
curl -L -o resource_hacker.zip http://www.angusj.com/resourcehacker/resource_hacker.zip
echo Распаковываем Resource Hacker...
powershell -command "Expand-Archive -Path resource_hacker.zip -DestinationPath reshacker"
echo Добавляем иконку к EXE-файлу...
reshacker\ResourceHacker.exe -open "dist\Калькулятор_Хеджирования_Uniswap_V3.exe" -save "dist\Калькулятор_Хеджирования_Uniswap_V3_с_иконкой.exe" -action addoverwrite -res "icon.ico" -mask ICONGROUP,MAINICON,0
echo Готово! Файл с иконкой: "dist\Калькулятор_Хеджирования_Uniswap_V3_с_иконкой.exe" 