@echo off
echo Downloading Resource Hacker...
curl -L -o resource_hacker.zip http://www.angusj.com/resourcehacker/resource_hacker.zip
echo Extracting Resource Hacker...
powershell -command "Expand-Archive -Path resource_hacker.zip -DestinationPath reshacker -Force"
echo Creating copy of the executable...
copy "dist\Калькулятор_Хеджирования_Uniswap_V3.exe" "dist\hedging_calculator_with_icon.exe"
echo Adding icon to the EXE file...
reshacker\ResourceHacker.exe -open "dist\hedging_calculator_with_icon.exe" -save "dist\hedging_calculator_with_icon.exe" -action addoverwrite -res "icon.ico" -mask ICONGROUP,MAINICON,0
echo Done! The file with icon is: "dist\hedging_calculator_with_icon.exe" 